2024-11-05 15:42:00,071 | test_run | Module_12_4 | WARNING: Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\volch\PycharmProjects\pythonProject\Module_12_4.py", line 24, in test_run
    tr = Runner(2)
         ^^^^^^^^^
  File "C:\Users\volch\PycharmProjects\pythonProject\Module_12_4_Test.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-05 15:42:00,072 | test_walk | Module_12_4 | WARNING: Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\volch\PycharmProjects\pythonProject\Module_12_4.py", line 13, in test_walk
    tw = Runner('Test1', speed=-2)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\volch\PycharmProjects\pythonProject\Module_12_4_Test.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -2
